/**
 * Account Commands
 *
 * Commands for managing Account aggregates (User/Organization/Bot creation and updates).
 *
 * Naming Convention: Imperative verb + noun (CreateAccount, UpdateAccount, etc.)
 */

import { Command, CommandMetadata } from '@ng-events/core-engine';
import { AccountType, AccountMetadata } from '../types/account.types';

/**
 * CreateAccountCommand - Create a new account (User/Organization/Bot)
 */
export interface CreateAccountCommandData {
  /**
   * Account ID (generated by client or system)
   */
  readonly accountId: string;

  /**
   * Type of account to create
   */
  readonly accountType: AccountType;

  /**
   * Type-specific metadata
   */
  readonly metadata: AccountMetadata;
}

export interface CreateAccountCommand extends Command<CreateAccountCommandData> {
  readonly commandType: 'CreateAccountCommand';
}

/**
 * UpdateAccountCommand - Update account metadata
 */
export interface UpdateAccountCommandData {
  /**
   * Account ID to update
   */
  readonly accountId: string;

  /**
   * Updated metadata (partial)
   */
  readonly metadata: Partial<AccountMetadata>;
}

export interface UpdateAccountCommand extends Command<UpdateAccountCommandData> {
  readonly commandType: 'UpdateAccountCommand';
}

/**
 * SuspendAccountCommand - Suspend an account
 */
export interface SuspendAccountCommandData {
  /**
   * Account ID to suspend
   */
  readonly accountId: string;

  /**
   * Reason for suspension
   */
  readonly reason: string;
}

export interface SuspendAccountCommand extends Command<SuspendAccountCommandData> {
  readonly commandType: 'SuspendAccountCommand';
}

/**
 * ReactivateAccountCommand - Reactivate a suspended account
 */
export interface ReactivateAccountCommandData {
  /**
   * Account ID to reactivate
   */
  readonly accountId: string;
}

export interface ReactivateAccountCommand extends Command<ReactivateAccountCommandData> {
  readonly commandType: 'ReactivateAccountCommand';
}

/**
 * DeleteAccountCommand - Soft delete an account
 */
export interface DeleteAccountCommandData {
  /**
   * Account ID to delete
   */
  readonly accountId: string;

  /**
   * Reason for deletion
   */
  readonly reason?: string;
}

export interface DeleteAccountCommand extends Command<DeleteAccountCommandData> {
  readonly commandType: 'DeleteAccountCommand';
}

// END OF FILE
