version: '1.0'

mcp:
  enabled: true
  servers_config: '.github/copilot/mcp-servers.json'

instructions:
  - '.github/instructions/mcp-integration.instructions.md'
  - '.github/instructions/angular.instructions.md'

version: 1

agents:
  playwright:
    description: Runs Playwright MCP for browser-based testing
    capabilities:
      - run
      - test
      - browser
      - mcp
