version: '1.0'

mcp:
  enabled: true
  servers_config: '.github/copilot/mcp-servers.json'

instructions:
  - '.github/instructions/mcp-integration.instructions.md'
  - '.github/instructions/angular.instructions.md'

agents:
  playwright:
    description: >
      Executes real browser automation using Playwright MCP.
      Responsible for navigation, login, UI validation, screenshots, and reporting.
    mcp_servers:
      - playwright-mcp-server
    capabilities:
      - browser
      - automation
      - testing
      - mcp
