#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
export NODE_OPTIONS="--max-old-space-size=4096"
# Temporarily disabled - type-check issues in existing codebase
# npx --no-install tsc -p tsconfig.json --noEmit
npx --no-install lint-staged
